spring.application.name=Block2

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#Liquibase та Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase-changelog.xml